PrincessUgbobuaku/group-IT1_MobileGlow_Car_Wash

src/main/java/za/ac/cput/domain/booking/Vehicle.java
src/main/java/za/ac/cput/domain/user/Customer.java

Vehicle and Customer Domain Classes completed

Issue #6 completed

---

src/main/java/za/ac/cput/domain/user/employee/Accountant.java
src/main/java/za/ac/cput/domain/user/employee/Manager.java
src/main/java/za/ac/cput/domain/user/employee/WashAttendant.java

Updated user. Employee classes #4

user classes

---

src/main/java/za/ac/cput/domain/generic/Address.java
src/main/java/za/ac/cput/domain/generic/Contact.java
src/main/java/za/ac/cput/domain/review/ServiceReview.java

Address, Contact and Service Review classes

---

src/main/java/za/ac/cput/domain/user/Login.java
src/main/java/za/ac/cput/domain/user/Role.java
src/main/java/za/ac/cput/domain/user/User.java
src/main/java/za/ac/cput/domain/user/UserRole.java

Updated Classes

---

src/main/java/za/ac/cput/Main.java
src/main/java/za/ac/cput/domain/booking/Booking.java
src/main/java/za/ac/cput/domain/booking/CleaningService.java
src/main/java/za/ac/cput/domain/payment/Payment.java

Payment, Booking, CleaningService, Main closes #5

My classes

---

src/main/java/za/ac/cput/Main.java
src/main/java/za/ac/cput/domain/booking/Booking.java
src/main/java/za/ac/cput/domain/payment/Payment.java

More updates

---

src/main/java/za/ac/cput/domain/generic/Address.java
src/main/java/za/ac/cput/domain/generic/Contact.java

Added builder pattern classes #7

Address and Contact Builder Pattern

---

pom.xml
src/main/java/za/ac/cput/domain/booking/Vehicle.java
src/main/java/za/ac/cput/domain/user/Customer.java
src/main/java/za/ac/cput/factory/booking/VehicleFactory.java
src/main/java/za/ac/cput/factory/user/CustomerFactory.java
src/main/java/za/ac/cput/util/Helper.java
src/test/java/za/ac/cput/factory/booking/VehicleFactoryTest.java
src/test/java/za/ac/cput/factory/user/CustomerFactoryTest.java

factory, tests, helper and pom file

issue #21 completed

---

src/main/java/za/ac/cput/factory/generic/AddressFactory.java
src/main/java/za/ac/cput/factory/generic/ContactFactory.java
src/main/java/za/ac/cput/factory/review/ServiceReviewFactory.java
src/main/java/za/ac/cput/util/Helper.java
src/test/java/za/ac/cput/factory/generic/AddressFactoryTest.java
src/test/java/za/ac/cput/factory/generic/ContactFactoryTest.java
src/test/java/za/ac/cput/factory/review/ServiceReviewFactoryTest.java

Factory & Factory Tests for: Address, Contact and Service Review #22

Factory & Factory Tests for Address, Contact and Service Review

---

README.md
pom.xml
src/main/java/za/ac/cput/domain/booking/Booking.java
src/main/java/za/ac/cput/domain/user/Login.java
src/main/java/za/ac/cput/domain/user/Role.java
src/main/java/za/ac/cput/domain/user/User.java
src/main/java/za/ac/cput/domain/user/UserRole.java
src/main/java/za/ac/cput/factory/user/LoginFactory.java
src/main/java/za/ac/cput/factory/user/RoleFactory.java
src/main/java/za/ac/cput/factory/user/UserFactory.java
src/main/java/za/ac/cput/factory/user/UserRoleFactory.java
src/main/java/za/ac/cput/util/Helper.java
src/test/java/za/ac/cput/factory/user/LoginFactoryTest.java
src/test/java/za/ac/cput/factory/user/RoleFactoryTest.java
src/test/java/za/ac/cput/factory/user/UserFactoryTest.java
src/test/java/za/ac/cput/factory/user/UserRoleFactoryTest.java

Issue #20 
All classes created and updated

Factory and Factory test

---

src/main/java/za/ac/cput/repository/IRepository.java
src/main/java/za/ac/cput/repository/user/LoginRepository.java
src/main/java/za/ac/cput/repository/user/RoleRepository.java
src/main/java/za/ac/cput/repository/user/UserRepository.java
src/main/java/za/ac/cput/repository/user/UserRoleRepository.java
src/main/java/za/ac/cput/repository/user/impl/LoginRepositoryImpl.java
src/main/java/za/ac/cput/repository/user/impl/RoleRepositoryImpl.java
src/main/java/za/ac/cput/repository/user/impl/UserRepositoryImpl.java
src/main/java/za/ac/cput/repository/user/impl/UserRoleRepositoryImpl.java
src/test/java/za/ac/cput/repository/user/impl/LoginRepositoryImplTest.java
src/test/java/za/ac/cput/repository/user/impl/RoleRepositoryImplTest.java
src/test/java/za/ac/cput/repository/user/impl/UserRepositoryImplTest.java
src/test/java/za/ac/cput/repository/user/impl/UserRoleRepositoryImplTest.java

Updated Repository and Repository Test classes

---

src/main/java/za/ac/cput/domain/review/ServiceReview.java
src/main/java/za/ac/cput/repository/generic/AddressRepository.java
src/main/java/za/ac/cput/repository/generic/ContactRepository.java
src/main/java/za/ac/cput/repository/generic/impl/IAddressRepository.java
src/main/java/za/ac/cput/repository/generic/impl/IContactRepository.java
src/main/java/za/ac/cput/repository/review/ServiceReviewRepository.java
src/main/java/za/ac/cput/repository/review/impl/IServiceReviewRepository.java
src/test/java/za/ac/cput/repository/generic/AddressRepositoryTest.java
src/test/java/za/ac/cput/repository/generic/ContactRepositoryTest.java
src/test/java/za/ac/cput/repository/review/ServiceReviewRepositoryTest.java

Repository & Repository Test for ServiceReview, Contact, Address #43

Repository & RepositoryTest: ServiceReview, Contact, Address

---

src/main/java/za/ac/cput/service/generic/AddressService.java
src/main/java/za/ac/cput/service/generic/ContactService.java
src/main/java/za/ac/cput/service/review/ServiceReviewService.java

These are my Service Classes for Address, Contact and Service Review.

Service Classes for Address, Contact and Service Review

---

src/main/java/za/ac/cput/domain/generic/Address.java
src/main/java/za/ac/cput/domain/generic/Contact.java
src/main/java/za/ac/cput/domain/review/ServiceReview.java
src/main/java/za/ac/cput/factory/generic/ContactFactory.java
src/main/java/za/ac/cput/factory/review/ServiceReviewFactory.java
src/main/java/za/ac/cput/factory/user/employee/AccountantFactory.java

Domain classes for Address, Contact, and ServiceReview

Address, Contact, and ServiceReview Domian classes

---

src/main/java/za/ac/cput/domain/user/User.java

small change made to column name to match contact domain

updated User domain

---

frontend/src/screens/auth/AddressDetails.js
frontend/src/screens/auth/Login.js
frontend/src/screens/auth/RoleSelection.js
frontend/src/screens/auth/SignUp.js
src/main/java/za/ac/cput/controller/user/employee/AccountantController.java
src/main/java/za/ac/cput/service/user/employee/impl/AccountantServiceImpl.java

…ommented out.  also made changes in AccountantController.

Made chages AccountantServiceImpl and AccountantController

---

frontend/src/screens/components/Footer.css
frontend/src/screens/components/Footer.js

This is the Footer.js class along with Footer.css

Frontend: Footer.js class and Footer.css

---

pom.xml
src/main/java/za/ac/cput/config/JWTAuthenticationFilter.java
src/main/java/za/ac/cput/config/SecurityConfig.java
src/main/java/za/ac/cput/controller/user/LoginController.java
src/main/java/za/ac/cput/controller/user/employee/WashAttendantController.java
src/main/java/za/ac/cput/factory/user/LoginFactory.java
src/main/java/za/ac/cput/repository/user/IUserRepository.java
src/main/java/za/ac/cput/service/user/CustomUserDetailsService.java
src/main/java/za/ac/cput/service/user/CustomerService.java
src/main/java/za/ac/cput/service/user/JWTService.java
src/main/java/za/ac/cput/service/user/LoginService.java
src/main/java/za/ac/cput/service/user/UserService.java
src/main/java/za/ac/cput/service/user/employee/AccountantService.java
src/main/java/za/ac/cput/service/user/employee/ManagerService.java
src/main/java/za/ac/cput/service/user/employee/WashAttendantService.java
src/main/java/za/ac/cput/util/PasswordHelper.java
src/test/java/za/ac/cput/service/user/employee/AccountantServiceTest.java

Security Implementation with JWT Token.

Security Implementation with JWT Token

---

frontend/src/App.js
frontend/src/screens/auth/AddressDetails.js
frontend/src/screens/auth/RoleSelection.js
frontend/src/screens/auth/SignUp.js
frontend/src/screens/components/Navbar.css
frontend/src/screens/components/Navbar.js

Updated App.js, AddressDetails.js, Navbar.css, Navbar.js, RoleSelection.js, SignUp.js class

App.js, AddressDetails.js, Navbar.css, Navbar.js, RoleSelection.js, SignUp.js class

---

frontend/src/App.js
frontend/src/screens/EditCustomerProfile.jsx
frontend/src/screens/EditEmployeeProfile.jsx
frontend/src/screens/ProfilePage.css
frontend/src/screens/ProfilePage.jsx
frontend/src/services/api.js
frontend/src/services/employeeService.js
src/main/java/za/ac/cput/controller/user/employee/AccountantController.java
src/main/java/za/ac/cput/controller/user/employee/ManagerController.java
src/main/java/za/ac/cput/controller/user/employee/WashAttendantController.java

Updated styling  of profiles for both Employees and Customer.

Profile updates
